name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            
            - name: Setup .NET 8
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore MovieApp.csproj
            
            - name: Build App
              run: dotnet build MovieApp.csproj -c Release --no-restore